name: Release

on:
  push:
    branches:
    - mkroman/release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a # master
      with:
        toolchain: stable
        components: clippy
        targets: ${{ matrix.target }}
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-
    - name: Run Clippy check
      uses: clechasseur/rs-clippy-check@6489db34e7d7a162364f8ee3d7ad2cd1060dc1d7 # v3.0.3
      with:
        args: --all-features --target ${{ matrix.target }}
    - name: Run cargo tests
      run: cargo test --target ${{ matrix.target }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
    - test
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a # master
      with:
        toolchain: stable
        components: clippy
        targets: ${{ matrix.target }}
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.target }}-
    - name: Build release
      run: cargo build --release --target ${{ matrix.target }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: op2secret-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/op2secret
